### ISSUE TITLE
IMG tag vulnerability

### ISSUE THREAD

**Issue by aadtyn** [SoulNinja-dev/twt-news#20]
when creating a post it doesn't filter the img tag meaning you can just do `<img src="any url"/>` <img src="https://yip.su/1P9Zu7"/> and whoever visits the site will automatically visit that url trying to fetch an image

this allows for the implementation of Ip loggers etc.

**Comment by SoulNinja-dev** [comment]
<img src="https://yip.su/1P9Zu7"/>

**Comment by FirePlank** [comment]
this issue was found by your truly, fireplank

**Comment by aadtyn** [comment]
fixed for now, but need a better solution

**Comment by FirePlank** [comment]
you didnt tho

**Comment by FirePlank** [comment]
srcset is still one

**Comment by aadtyn** [comment]
fixed with regex by @Shiv-Patil 

only github and discord images allowed 👍🏻
