### ISSUE TITLE
Username XSS is still possible!!!

### ISSUE THREAD

**Issue by FirePlank** [SoulNinja-dev/twt-news#24]
With a specially crafted username such as `<div onmousemove="alert('XSS');"/>` it is possible to break out of the div container that displays the user's username in a post.
![image](https://user-images.githubusercontent.com/44502537/148617566-e516fa19-4b1d-469b-9a42-a05473c43175.png)
in the above image the XSS would trigger if the user where to hover over the specified area. I could probably get it to execute on page load but I am too lazy/unskilled to figure it out because it has to be under 50 chars because of username length restrictions.

**Comment by aadtyn** [comment]
fixed
